apiVersion: v1
kind: Service
metadata:
  name: urlchecker
  namespace: url-checker
  labels:
    app: urlchecker
spec:
  type: NodePort
  selector:
    app: urlchecker
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
