global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "urlstatuscecker"
    static_configs:
      - targets: ["urlstatuscecker:8080"]
        labels:
          service: "url-status-checker"
